apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
apiServer:
  extraArgs:
    enable-priority-and-fairness: false
    max-connection-bytes-per-sec: 0
    max-mutating-requests-inflight: 0
    max-requests-inflight: 0
etcd:
  extraArgs:
    listen-metrics-urls: "http://0.0.0.0:2381" # For Prometheus metrics scrapping
controllerManager:
  extraArgs:
    bind-address: "0.0.0.0"  # For Prometheus metrics scrapping
    kube-api-qps: 50000
    kube-api-burst: 100000
scheduler:
  extraArgs:
    bind-address: "0.0.0.0" # For Prometheus metrics scrapping
    kube-api-qps: 50000
    kube-api-burst: 100000

---
# Configure kubelet for large pod limits.
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
kubeAPIQPS: 50000
kubeAPIBurst: 100000
configMapAndSecretChangeDetectionStrategy: "Watch"
