apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/hyhe/helloworld
          env:
            - name: TARGET
              value: "there!"