apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: test-func
  namespace: default
spec:
  template:
    metadata:
        autoscaling.knative.dev/target-burst-capacity: "-1"  # Put activator always in the path explicitly.
        autoscaling.knative.dev/max-scale: "200"  # Maximum instances limit of Azure.

    spec:
      containerConcurrency: 1
      containers:
        - image: docker.io/hyhe/test-func:latest

            
