apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  namespace: default
spec:
  template:
    spec:
      containers:
        # - image: gaow0007/trace_function_gpt:latest
        - image: gaow0007/trace_function_gpt_gpu:latest
          imagePullPolicy: Always
          ports:
            - name: h2c # For gRPC support
              containerPort: 80
          resources:
            limits:
              cpu: 4000m
              nvidia.com/gpu: 1
            requests:
              cpu: 4000m
              memory: 2000Mi
              nvidia.com/gpu: 1
          volumeMounts:
              - name: data-volume
                mountPath: /app/checkpoints/hf_model/models--gpt2-large/
      volumes:
        - name: data-volume
          hostPath:
            path: /root/checkpoints/hf_model/models--gpt2-large/