apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  namespace: default
spec:
  template:
    spec:
      containers:
        # - image: gaow0007/trace_function_gpt:latest
        - image: gaow0007/trace_function_gpt:latest
          imagePullPolicy: Always
          ports:
            - name: h2c # For gRPC support
              containerPort: 80
