name: Run Tests
on:
  push:
    branches:    
      - '*'  # matches every branch that doesn't contain a '/'
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request: 
    branches: 
      - main
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  runt-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Test internal
        run: go test -v ./internal/test/
